### PR TITLE
Build fix: Add missing include

### PR DESCRIPTION
**Pull request by peters**

### CODE REVIEW

**Comment by peters** [comment]
@tomfinegan You could probably upstream this? :)

**Comment by tomfinegan** [comment]
Thanks for the heads up! I'll fix this upstream. In the future, please submit patches to chromium-review.googlesource.com. Patch submission guidelines are at the following link.

http://www.webmproject.org/code/contribute/submitting-patches/

You might have missed this note on the project landing page:
Mirror only. Please do not send pull requests. http://www.webmproject.org/code/

Anyway, I'll add the missing include today. Thanks again!

**Comment by tomfinegan** [comment]
fyi: https://chromium-review.googlesource.com/c/429871/

**Comment by peters** [comment]
@tomfinegan Thanks! I'll keep that in mind next time :)

**Pull request closed without merging**
